export const Events = {
  MEDIA_ATTACHED: 'mediaAttached',
  MEDIA_DETACHED: 'mediaDetached',
  BUFFER_RESET: 'bufferReset',
  BUFFER_CODECS: 'bufferCodecs',
  BUFFER_APPENDING: 'bufferAppending',
  BUFFER_APPENDED: 'bufferAppended',
  BUFFER_FLUSHING: 'bufferFlushing',
  BUFFER_FLUSHED: 'bufferFlushed',
  MANIFEST_LOADING: 'manifestLoading',
  MANIFEST_LOADED: 'manifestLoaded',
  MANIFEST_PARSED: 'manifestParsed',
  LEVEL_SWITCHING: 'levelSwitching',
  LEVEL_SWITCHED: 'levelSwitched',
  LEVEL_LOADING: 'levelLoading',
  LEVEL_LOADED: 'levelLoaded',
  LEVEL_UPDATED: 'levelUpdated',
  FRAG_LOADING: 'fragLoading',
  FRAG_LOAD_PROGRESS: 'fragLoadProgress',
  FRAG_LOADED: 'fragLoaded',
  FRAG_DECRYPTED: 'fragDecrypted',
  FRAG_PARSING_INIT_SEGMENT: 'fragParsingInitSegment',
  FRAG_PARSING_DATA: 'fragParsingData',
  FRAG_PARSED: 'fragParsed',
  FRAG_BUFFERED: 'fragBuffered',
  AUDIO_TRACKS_UPDATED: 'audioTracksUpdated',
  AUDIO_TRACK_SWITCHING: 'audioTrackSwitching',
  AUDIO_TRACK_SWITCHED: 'audioTrackSwitched',
  SUBTITLE_TRACKS_UPDATED: 'subtitleTracksUpdated',
  SUBTITLE_TRACK_SWITCH: 'subtitleTrackSwitch',
  ERROR: 'hlsError',
  DESTROYING: 'hlsDestroying',
} as const;

export type Event = (typeof Events)[keyof typeof Events];
